export const COLOR_TILE_BOARD = [
  {col: 0, row: 0, w: 3, lb: 'TL'},
  {col: 0, row: 4, w: 4, lb: 'TW'},
  {col: 0, row: 7, w: 1, lb: 'DL'},
  {col: 0, row: 10, w: 4, lb: 'TW'},
  {col: 0, row: 14, w: 3, lb: 'TL'},
  {col: 1, row: 1, w: 1, lb: 'DL'},
  {col: 1, row: 5, w: 3, lb: 'TL'},
  {col: 1, row: 9, w: 3, lb: 'TL'},
  {col: 1, row: 13, w: 1, lb: 'DL'},
  {col: 2, row: 2, w: 2, lb: 'DW'},
  {col: 2, row: 6, w: 3, lb: 'TL'},
  {col: 2, row: 8, w: 3, lb: 'TL'},
  {col: 2, row: 12, w: 2, lb: 'DW'},
  {col: 3, row: 3, w: 3, lb: 'TL'},
  {col: 3, row: 7, w: 2, lb: 'DW'},
  {col: 3, row: 11, w: 3, lb: 'TL'},
  {col: 4, row: 0, w: 4, lb: 'TW'},
  {col: 4, row: 4, w: 2, lb: 'DW'},
  {col: 4, row: 6, w: 1, lb: 'DL'},
  {col: 4, row: 8, w: 1, lb: 'DL'},
  {col: 4, row: 10, w: 2, lb: 'DW'},
  {col: 4, row: 14, w: 4, lb: 'TW'},
  {col: 5, row: 1, w: 3, lb: 'TL'},
  {col: 5, row: 5, w: 3, lb: 'TL'},
  {col: 5, row: 9, w: 3, lb: 'TL'},
  {col: 5, row: 13, w: 3, lb: 'TL'},
  {col: 6, row: 2, w: 1, lb: 'DL'},
  {col: 6, row: 4, w: 1, lb: 'DL'},
  {col: 6, row: 10, w: 1, lb: 'DL'},
  {col: 6, row: 12, w: 1, lb: 'DL'},
  {col: 7, row: 0, w: 1, lb: 'DL'},
  {col: 7, row: 3, w: 2, lb: 'DW'},
  {col: 7, row: 7, w: -1, lb: 'STAR'},
  {col: 7, row: 11, w: 2, lb: 'DW'},
  {col: 7, row: 14, w: 1, lb: 'DL'},
  {col: 8, row: 2, w: 1, lb: 'DL'},
  {col: 8, row: 4, w: 1, lb: 'DL'},
  {col: 8, row: 10, w: 1, lb: 'DL'},
  {col: 8, row: 12, w: 1, lb: 'DL'},
  {col: 9, row: 1, w: 3, lb: 'TL'},
  {col: 9, row: 5, w: 3, lb: 'TL'},
  {col: 9, row: 9, w: 3, lb: 'TL'},
  {col: 9, row: 13, w: 3, lb: 'TL'},
  {col: 10, row: 0, w: 4, lb: 'TW'},
  {col: 10, row: 4, w: 2, lb: 'DW'},
  {col: 10, row: 6, w: 1, lb: 'DL'},
  {col: 10, row: 8, w: 1, lb: 'DL'},
  {col: 10, row: 10, w: 2, lb: 'DW'},
  {col: 10, row: 14, w: 4, lb: 'TW'},
  {col: 11, row: 3, w: 3, lb: 'TL'},
  {col: 11, row: 7, w: 2, lb: 'DW'},
  {col: 11, row: 11, w: 3, lb: 'TL'},
  {col: 12, row: 2, w: 2, lb: 'DW'},
  {col: 12, row: 6, w: 3, lb: 'TL'},
  {col: 12, row: 8, w: 3, lb: 'TL'},
  {col: 12, row: 12, w: 2, lb: 'DW'},
  {col: 13, row: 1, w: 1, lb: 'DL'},
  {col: 13, row: 5, w: 3, lb: 'TL'},
  {col: 13, row: 9, w: 3, lb: 'TL'},
  {col: 13, row: 13, w: 1, lb: 'DL'},
  {col: 14, row: 0, w: 3, lb: 'TL'},
  {col: 14, row: 4, w: 4, lb: 'TW'},
  {col: 14, row: 7, w: 1, lb: 'DL'},
  {col: 14, row: 10, w: 4, lb: 'TW'},
  {col: 14, row: 14, w: 3, lb: 'TL'},
];

export const CHARS = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];

export const WEIGHTS = [
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  4,
  1,
  1,
  1,
  1,
  1,
  5,
  1,
  1,
  1,
];
