require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'master_mind' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'RNGetSocial', :path => '../node_modules/getsocial-react-native-sdk'

  target 'master_mindTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'master_mind-tvOS' do
  # Pods for master_mind-tvOS

  target 'master_mind-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
