const initialTiles = {
  en: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 2, value: 3},
    {char: 'D', amount: 4, value: 2},
    {char: 'E', amount: 10, value: 1},
    {char: 'F', amount: 2, value: 3},
    {char: 'G', amount: 4, value: 2},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 2, value: 7},
    {char: 'K', amount: 2, value: 6},
    {char: 'L', amount: 2, value: 2},
    {char: 'M', amount: 2, value: 3},
    {char: 'N', amount: 5, value: 1},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 2, value: 2},
    {char: 'Q', amount: 1, value: 9},
    {char: 'R', amount: 7, value: 1},
    {char: 'S', amount: 5, value: 1},
    {char: 'T', amount: 5, value: 1},
    {char: 'U', amount: 5, value: 1},
    {char: 'V', amount: 2, value: 5},
    {char: 'W', amount: 2, value: 5},
    {char: 'X', amount: 1, value: 8},
    {char: 'Y', amount: 1, value: 5},
    {char: 'Z', amount: 1, value: 9},
    {char: ' ', amount: 2, value: 0},
  ],
  de: [
    {char: 'A', amount: 6, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 3, value: 3},
    {char: 'D', amount: 3, value: 2},
    {char: 'E', amount: 9, value: 1},
    {char: 'F', amount: 2, value: 3},
    {char: 'G', amount: 3, value: 2},
    {char: 'H', amount: 3, value: 2},
    {char: 'I', amount: 6, value: 1},
    {char: 'J', amount: 1, value: 7},
    {char: 'K', amount: 3, value: 4},
    {char: 'L', amount: 3, value: 2},
    {char: 'M', amount: 3, value: 3},
    {char: 'N', amount: 6, value: 1},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 2, value: 3},
    {char: 'Q', amount: 1, value: 9},
    {char: 'R', amount: 6, value: 1},
    {char: 'S', amount: 6, value: 1},
    {char: 'T', amount: 4, value: 1},
    {char: 'U', amount: 4, value: 1},
    {char: 'V', amount: 2, value: 5},
    {char: 'W', amount: 2, value: 3},
    {char: 'X', amount: 1, value: 9},
    {char: 'Y', amount: 1, value: 9},
    {char: 'Z', amount: 2, value: 2},
    {char: 'Ä', amount: 1, value: 7},
    {char: 'Ö', amount: 1, value: 7},
    {char: 'Ü', amount: 1, value: 7},
    {char: ' ', amount: 2, value: 0},
  ],
  hr: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 2, value: 4},
    {char: 'Č', amount: 1, value: 5},
    {char: 'Ć', amount: 1, value: 3},
    {char: 'D', amount: 3, value: 3},
    {char: 'Dž', amount: 1, value: 9},
    {char: 'Đ', amount: 1, value: 9},
    {char: 'E', amount: 8, value: 1},
    {char: 'F', amount: 2, value: 6},
    {char: 'G', amount: 2, value: 4},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 3, value: 1},
    {char: 'K', amount: 3, value: 2},
    {char: 'L', amount: 2, value: 2},
    {char: 'Lj', amount: 2, value: 4},
    {char: 'M', amount: 3, value: 2},
    {char: 'N', amount: 4, value: 1},
    {char: 'Nj', amount: 2, value: 4},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 3, value: 2},
    {char: 'R', amount: 3, value: 1},
    {char: 'S', amount: 4, value: 1},
    {char: 'Š', amount: 2, value: 4},
    {char: 'T', amount: 4, value: 1},
    {char: 'U', amount: 4, value: 1},
    {char: 'V', amount: 3, value: 2},
    {char: 'Z', amount: 2, value: 3},
    {char: 'Ž', amount: 2, value: 4},
    {char: ' ', amount: 2, value: 0},
  ],
  bo: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 2, value: 4},
    {char: 'Č', amount: 1, value: 5},
    {char: 'Ć', amount: 1, value: 3},
    {char: 'D', amount: 3, value: 3},
    {char: 'Dž', amount: 1, value: 9},
    {char: 'Đ', amount: 1, value: 9},
    {char: 'E', amount: 8, value: 1},
    {char: 'F', amount: 2, value: 6},
    {char: 'G', amount: 2, value: 4},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 3, value: 1},
    {char: 'K', amount: 3, value: 2},
    {char: 'L', amount: 2, value: 2},
    {char: 'Lj', amount: 2, value: 4},
    {char: 'M', amount: 3, value: 2},
    {char: 'N', amount: 4, value: 1},
    {char: 'Nj', amount: 2, value: 4},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 3, value: 2},
    {char: 'R', amount: 3, value: 1},
    {char: 'S', amount: 4, value: 1},
    {char: 'Š', amount: 2, value: 4},
    {char: 'T', amount: 4, value: 1},
    {char: 'U', amount: 4, value: 1},
    {char: 'V', amount: 3, value: 2},
    {char: 'Z', amount: 2, value: 3},
    {char: 'Ž', amount: 2, value: 4},
    {char: ' ', amount: 2, value: 0},
  ],
  csb: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 2, value: 4},
    {char: 'Č', amount: 1, value: 5},
    {char: 'Ć', amount: 1, value: 3},
    {char: 'D', amount: 3, value: 3},
    {char: 'Dž', amount: 1, value: 9},
    {char: 'Đ', amount: 1, value: 9},
    {char: 'E', amount: 8, value: 1},
    {char: 'F', amount: 2, value: 6},
    {char: 'G', amount: 2, value: 4},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 3, value: 1},
    {char: 'K', amount: 3, value: 2},
    {char: 'L', amount: 2, value: 2},
    {char: 'Lj', amount: 2, value: 4},
    {char: 'M', amount: 3, value: 2},
    {char: 'N', amount: 4, value: 1},
    {char: 'Nj', amount: 2, value: 4},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 3, value: 2},
    {char: 'R', amount: 3, value: 1},
    {char: 'S', amount: 4, value: 1},
    {char: 'Š', amount: 2, value: 4},
    {char: 'T', amount: 4, value: 1},
    {char: 'U', amount: 4, value: 1},
    {char: 'V', amount: 3, value: 2},
    {char: 'Z', amount: 2, value: 3},
    {char: 'Ž', amount: 2, value: 4},
    {char: ' ', amount: 2, value: 0},
  ],
  ru: [
    {char: 'А', amount: 8, value: 1},
    {char: 'Б', amount: 2, value: 4},
    {char: 'Ц', amount: 2, value: 3},
    {char: 'Ч', amount: 1, value: 5},
    {char: 'Ы', amount: 2, value: 4},
    {char: 'Д', amount: 4, value: 2},
    {char: 'Ь', amount: 3, value: 3},
    {char: 'Э', amount: 1, value: 7},
    {char: 'E', amount: 8, value: 1},
    {char: 'Ё', amount: 1, value: 4},
    {char: 'Ф', amount: 1, value: 9},
    {char: 'Г', amount: 2, value: 3},
    {char: 'Х', amount: 2, value: 4},
    {char: 'И', amount: 6, value: 1},
    {char: 'Й', amount: 2, value: 4},
    {char: 'K', amount: 4, value: 2},
    {char: 'Л', amount: 3, value: 2},
    {char: 'Я', amount: 3, value: 3},
    {char: 'M', amount: 3, value: 2},
    {char: 'Н', amount: 4, value: 1},
    {char: 'Ю', amount: 1, value: 7},
    {char: 'O', amount: 9, value: 1},
    {char: 'Ъ', amount: 1, value: 9},
    {char: 'П', amount: 4, value: 2},
    {char: 'Р', amount: 4, value: 1},
    {char: 'С', amount: 5, value: 1},
    {char: 'Ш', amount: 1, value: 7},
    {char: 'T', amount: 5, value: 1},
    {char: 'У', amount: 4, value: 1},
    {char: 'В', amount: 4, value: 2},
    {char: 'З', amount: 2, value: 4},
    {char: 'Ж', amount: 1, value: 6},
    {char: 'Щ', amount: 1, value: 9},
    {char: ' ', amount: 2, value: 0},
  ],
  rs: [
    {char: 'А', amount: 8, value: 1},
    {char: 'Б', amount: 2, value: 4},
    {char: 'Ц', amount: 2, value: 4},
    {char: 'Ч', amount: 1, value: 5},
    {char: 'Ћ', amount: 1, value: 4},
    {char: 'Д', amount: 3, value: 3},
    {char: 'Џ', amount: 1, value: 9},
    {char: 'Ђ', amount: 1, value: 9},
    {char: 'E', amount: 8, value: 1},
    {char: 'Ф', amount: 2, value: 6},
    {char: 'Г', amount: 2, value: 4},
    {char: 'Х', amount: 2, value: 4},
    {char: 'И', amount: 8, value: 1},
    {char: 'J', amount: 3, value: 3},
    {char: 'K', amount: 3, value: 2},
    {char: 'Л', amount: 3, value: 2},
    {char: 'Љ', amount: 1, value: 8},
    {char: 'M', amount: 3, value: 2},
    {char: 'Н', amount: 4, value: 1},
    {char: 'Њ', amount: 1, value: 6},
    {char: 'O', amount: 8, value: 1},
    {char: 'П', amount: 3, value: 2},
    {char: 'Р', amount: 3, value: 1},
    {char: 'С', amount: 4, value: 1},
    {char: 'Ш', amount: 2, value: 4},
    {char: 'T', amount: 5, value: 1},
    {char: 'У', amount: 4, value: 1},
    {char: 'В', amount: 3, value: 2},
    {char: 'З', amount: 2, value: 3},
    {char: 'Ж', amount: 2, value: 4},
    {char: ' ', amount: 2, value: 0},
  ],
  fr: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 2, value: 3},
    {char: 'D', amount: 4, value: 2},
    {char: 'E', amount: 16, value: 1},
    {char: 'F', amount: 2, value: 3},
    {char: 'G', amount: 2, value: 3},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 1, value: 7},
    {char: 'K', amount: 1, value: 9},
    {char: 'L', amount: 4, value: 1},
    {char: 'M', amount: 3, value: 3},
    {char: 'N', amount: 5, value: 1},
    {char: 'O', amount: 7, value: 1},
    {char: 'P', amount: 2, value: 2},
    {char: 'Q', amount: 1, value: 9},
    {char: 'R', amount: 6, value: 1},
    {char: 'S', amount: 5, value: 1},
    {char: 'T', amount: 5, value: 1},
    {char: 'U', amount: 5, value: 1},
    {char: 'V', amount: 2, value: 5},
    {char: 'W', amount: 1, value: 9},
    {char: 'X', amount: 1, value: 9},
    {char: 'Y', amount: 1, value: 9},
    {char: 'Z', amount: 1, value: 9},
    {char: ' ', amount: 2, value: 0},
  ],
  es: [
    {char: 'A', amount: 13, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 3, value: 3},
    {char: 'D', amount: 6, value: 2},
    {char: 'E', amount: 11, value: 1},
    {char: 'F', amount: 1, value: 5},
    {char: 'G', amount: 3, value: 2},
    {char: 'H', amount: 2, value: 3},
    {char: 'I', amount: 7, value: 1},
    {char: 'J', amount: 2, value: 5},
    {char: 'LL', amount: 1, value: 9},
    {char: 'L', amount: 5, value: 1},
    {char: 'M', amount: 2, value: 3},
    {char: 'N', amount: 5, value: 1},
    {char: 'O', amount: 8, value: 1},
    {char: 'P', amount: 2, value: 2},
    {char: 'Q', amount: 1, value: 6},
    {char: 'R', amount: 5, value: 2},
    {char: 'S', amount: 5, value: 1},
    {char: 'T', amount: 5, value: 1},
    {char: 'U', amount: 6, value: 1},
    {char: 'V', amount: 1, value: 5},
    {char: 'RR', amount: 1, value: 7},
    {char: 'X', amount: 1, value: 7},
    {char: 'Y', amount: 1, value: 5},
    {char: 'Z', amount: 1, value: 9},
    {char: 'CH', amount: 1, value: 6},
    {char: 'Ñ', amount: 1, value: 7},
    {char: ' ', amount: 2, value: 0},
  ],
  it: [
    {char: 'A', amount: 15, value: 1},
    {char: 'B', amount: 3, value: 4},
    {char: 'C', amount: 5, value: 2},
    {char: 'D', amount: 3, value: 2},
    {char: 'E', amount: 10, value: 1},
    {char: 'F', amount: 3, value: 4},
    {char: 'G', amount: 2, value: 7},
    {char: 'H', amount: 2, value: 6},
    {char: 'I', amount: 10, value: 1},
    {char: 'L', amount: 6, value: 2},
    {char: 'M', amount: 5, value: 2},
    {char: 'N', amount: 5, value: 2},
    {char: 'O', amount: 16, value: 1},
    {char: 'P', amount: 3, value: 4},
    {char: 'Q', amount: 1, value: 9},
    {char: 'R', amount: 7, value: 1},
    {char: 'S', amount: 5, value: 1},
    {char: 'T', amount: 5, value: 2},
    {char: 'U', amount: 5, value: 2},
    {char: 'V', amount: 3, value: 4},
    {char: 'Z', amount: 3, value: 6},
    {char: ' ', amount: 2, value: 0},
  ],
  pl: [
    {char: 'A', amount: 8, value: 1},
    {char: 'B', amount: 2, value: 3},
    {char: 'C', amount: 3, value: 3},
    {char: 'Y', amount: 5, value: 1},
    {char: 'Ć', amount: 1, value: 7},
    {char: 'D', amount: 3, value: 3},
    {char: 'Ł', amount: 3, value: 2},
    {char: 'Ę', amount: 1, value: 6},
    {char: 'E', amount: 8, value: 1},
    {char: 'F', amount: 1, value: 6},
    {char: 'G', amount: 2, value: 4},
    {char: 'H', amount: 2, value: 4},
    {char: 'I', amount: 8, value: 1},
    {char: 'J', amount: 2, value: 2},
    {char: 'K', amount: 3, value: 2},
    {char: 'L', amount: 3, value: 2},
    {char: 'Ó', amount: 1, value: 6},
    {char: 'M', amount: 3, value: 2},
    {char: 'N', amount: 6, value: 1},
    {char: 'Ń', amount: 1, value: 6},
    {char: 'O', amount: 7, value: 1},
    {char: 'P', amount: 4, value: 2},
    {char: 'R', amount: 4, value: 1},
    {char: 'S', amount: 4, value: 1},
    {char: 'Ś', amount: 1, value: 6},
    {char: 'T', amount: 3, value: 1},
    {char: 'U', amount: 3, value: 1},
    {char: 'W', amount: 5, value: 1},
    {char: 'Z', amount: 5, value: 1},
    {char: 'Ź', amount: 1, value: 9},
    {char: 'Ż', amount: 1, value: 6},
    {char: 'Ą', amount: 1, value: 7},
    {char: ' ', amount: 2, value: 0},
  ],
  mk: [
    {char: 'А', amount: 8, value: 1},
    {char: 'Б', amount: 3, value: 3},
    {char: 'Ц', amount: 1, value: 4},
    {char: 'Ч', amount: 1, value: 5},
    {char: 'Ѓ', amount: 1, value: 4},
    {char: 'Д', amount: 4, value: 2},
    {char: 'Џ', amount: 1, value: 9},
    {char: 'Ќ', amount: 1, value: 6},
    {char: 'E', amount: 8, value: 1},
    {char: 'Ф', amount: 2, value: 6},
    {char: 'Г', amount: 4, value: 3},
    {char: 'Х', amount: 2, value: 4},
    {char: 'И', amount: 8, value: 1},
    {char: 'J', amount: 3, value: 3},
    {char: 'K', amount: 3, value: 2},
    {char: 'Л', amount: 3, value: 2},
    {char: 'Љ', amount: 1, value: 6},
    {char: 'M', amount: 4, value: 2},
    {char: 'Н', amount: 4, value: 1},
    {char: 'Њ', amount: 1, value: 6},
    {char: 'O', amount: 8, value: 1},
    {char: 'П', amount: 5, value: 1},
    {char: 'Р', amount: 4, value: 1},
    {char: 'С', amount: 4, value: 1},
    {char: 'Ш', amount: 1, value: 7},
    {char: 'T', amount: 5, value: 1},
    {char: 'У', amount: 3, value: 2},
    {char: 'В', amount: 4, value: 2},
    {char: 'З', amount: 2, value: 4},
    {char: 'Ж', amount: 2, value: 5},
    {char: 'S', amount: 2, value: 3},
    {char: ' ', amount: 2, value: 0},
  ],
};
exports.initialBag = (language) => {
  let tiles = initialTiles[language ? language : 'en'];
  if (!tiles) {
    tiles = initialTiles.en;
  }
  const bag = [];
  tiles.map((tile) => {
    Array(tile.amount)
      .fill(0)
      .map(() => {
        bag.push({
          letter: tile.char,
          value: tile.value,
          status: 'bag',
        });
      });
  });
  return bag;
};
